'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Public Class ticket
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VisualizzaBiglietti.ticket", GetType(ticket).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Cognome.
    '''</summary>
    Public Shared ReadOnly Property cognome() As String
        Get
            Return ResourceManager.GetString("cognome", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Inserire il cognome.
    '''</summary>
    Public Shared ReadOnly Property cognomeObbligatorio() As String
        Get
            Return ResourceManager.GetString("cognomeObbligatorio", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Per visualizzare i biglietti compila tutti i dati per ogni singolo biglietto.
    '''</summary>
    Public Shared ReadOnly Property compilacampi() As String
        Get
            Return ResourceManager.GetString("compilacampi", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Conferma.
    '''</summary>
    Public Shared ReadOnly Property conferma() As String
        Get
            Return ResourceManager.GetString("conferma", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Si è verificato un errore durante il salvataggio anagrafica.
    '''</summary>
    Public Shared ReadOnly Property erroreAnagrafica() As String
        Get
            Return ResourceManager.GetString("erroreAnagrafica", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Attendere prego.....
    '''</summary>
    Public Shared ReadOnly Property loading() As String
        Get
            Return ResourceManager.GetString("loading", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Nome.
    '''</summary>
    Public Shared ReadOnly Property nome() As String
        Get
            Return ResourceManager.GetString("nome", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Inserire il nome.
    '''</summary>
    Public Shared ReadOnly Property nomeObbligatorio() As String
        Get
            Return ResourceManager.GetString("nomeObbligatorio", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Biglietto n°:.
    '''</summary>
    Public Shared ReadOnly Property numBiglietto() As String
        Get
            Return ResourceManager.GetString("numBiglietto", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Prevendita.
    '''</summary>
    Public Shared ReadOnly Property prevendita() As String
        Get
            Return ResourceManager.GetString("prevendita", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Prezzo.
    '''</summary>
    Public Shared ReadOnly Property prezzo() As String
        Get
            Return ResourceManager.GetString("prezzo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Totale.
    '''</summary>
    Public Shared ReadOnly Property totale() As String
        Get
            Return ResourceManager.GetString("totale", resourceCulture)
        End Get
    End Property
End Class
