'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX, quindi eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto Visual Studio.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ticket
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager memorizzata nella cache da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.ticket", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte
        '''  le ricerche di risorse eseguite con questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Cognome.
        '''</summary>
        Friend Shared ReadOnly Property cognome() As String
            Get
                Return ResourceManager.GetString("cognome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Inserire il cognome.
        '''</summary>
        Friend Shared ReadOnly Property cognomeObbligatorio() As String
            Get
                Return ResourceManager.GetString("cognomeObbligatorio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Per visualizzare i biglietti compila tutti i dati per ogni singolo biglietto.
        '''</summary>
        Friend Shared ReadOnly Property compilacampi() As String
            Get
                Return ResourceManager.GetString("compilacampi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Conferma.
        '''</summary>
        Friend Shared ReadOnly Property conferma() As String
            Get
                Return ResourceManager.GetString("conferma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Si è verificato un errore durante il salvataggio anagrafica.
        '''</summary>
        Friend Shared ReadOnly Property erroreAnagrafica() As String
            Get
                Return ResourceManager.GetString("erroreAnagrafica", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Attendere prego.....
        '''</summary>
        Friend Shared ReadOnly Property loading() As String
            Get
                Return ResourceManager.GetString("loading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Nome.
        '''</summary>
        Friend Shared ReadOnly Property nome() As String
            Get
                Return ResourceManager.GetString("nome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Inserire il nome.
        '''</summary>
        Friend Shared ReadOnly Property nomeObbligatorio() As String
            Get
                Return ResourceManager.GetString("nomeObbligatorio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Biglietto n°:.
        '''</summary>
        Friend Shared ReadOnly Property numBiglietto() As String
            Get
                Return ResourceManager.GetString("numBiglietto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Prevendita.
        '''</summary>
        Friend Shared ReadOnly Property prevendita() As String
            Get
                Return ResourceManager.GetString("prevendita", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Prezzo.
        '''</summary>
        Friend Shared ReadOnly Property prezzo() As String
            Get
                Return ResourceManager.GetString("prezzo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Totale.
        '''</summary>
        Friend Shared ReadOnly Property totale() As String
            Get
                Return ResourceManager.GetString("totale", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
